version: '2'
services:
  activemq:
    image: rmohr/activemq:5.14.5
    container_name: activemq
    network_mode: "host"
    environment:
    - "ACTIVEMQ_SUNJMX_START=-Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
    volumes:
      - /data/activemq/data:/data/activemq
      - /etc/docker-compose/activemq/conf:/opt/activemq/conf
      - /etc/localtime:/etc/localtime:ro
