version: '2'
services:
  activemq:
    image: rmohr/activemq:5.14.5
    container_name: activemq
    network_mode: "host"
    environment:
    - "ACTIVEMQ_SUNJMX_START=-Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
    volumes:
      - /data/activemq/data:/data/activemq
      - /etc/docker-compose/activemq/conf:/opt/activemq/conf
      - /etc/localtime:/etc/localtime:ro

  redis:
    image: redis:3.2.11
    container_name: redis
    network_mode: "host"
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - /data/redis/data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/docker-compose/redis.conf:/usr/local/etc/redis/redis.conf

  sentinel: 
    image: s7anley/redis-sentinel-docker:3.2.11
    container_name: sentinel
    network_mode: "host"
    environment:
      - MASTER_NAME=mymaster
      - MASTER=host1:6379
      - SLAVES=host2:6379;host3:6379

  zookeeper:
      image: zookeeper
      container_name: zookeeper
      restart: always
      hostname: zoo
      network_mode: "host"


  zoo1:
    image: zookeeper
    container_name: zookeeper1
    restart: always
    hostname: zoo1
    network_mode: "host"    
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=host2:2888:3888 server.3=host3:2888:3888

  zoo2:
    image: zookeeper
    container_name: zookeeper2
    restart: always
    hostname: zoo2
    network_mode: "host"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=host1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=host3:2888:3888

  zoo3:
    image: zookeeper
    container_name: zookeeper3
    restart: always
    hostname: zoo3
    network_mode: "host"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=host1:2888:3888 server.2=host2:2888:3888 server.3=0.0.0.0:2888:3888

  nginx:
    image: nginx
    container_name: nginx
    volumes:
     - /etc/docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"

  hadoop:
    image: logistimo/hadoop:2.3.0-cdh5.1.3-3
    container_name: hadoop
    restart: always
    environment:
      - RUN_NN=y
      - RUN_DN=y
      - RUN_HTTPFS=y
    ports:
      - "50010:50010"
      - "50020:50020"
      - "50070:50070"
      - "50075:50075"
      - "50090:50090"
      - "8020:8020"
      - "9000:9000"
      - "19888:19888"
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
      - "8040:8040"
      - "8042:8042"
      - "8088:8088"
      - "49707:49707"
      - "2122:2122"
      - "14000:14000"
    volumes:
      - /data/hadoop/data:/usr/local/hadoop-2.3.0-cdh5.1.3/data
      - /data/hadoop/logs:/usr/local/hadoop-2.3.0-cdh5.1.3/logs
      - /etc/docker-compose/hadoop-conf:/usr/local/hadoop-2.3.0-cdh5.1.3/etc/hadoop

  mongo:
    image: mongo:latest
    container_name: mongo
    network_mode: "host"
    ports:
      - "27017:27017"
    volumes:
      - /etc/docker-compose/mongo/mongod.conf:/etc/mongod.conf:ro
      - /data/mongodb:/data/db

  mariadb:
    image: mariadb:10.1.22
    container_name: mariadb
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /data/mysql:/var/lib/mysql

  locations:
    image: logistimo/locations-service:latest
    container_name: locations
    ports:
      - "9090:9090"
    environment:
      - MYSQL_LOC_HOST=jdbc:mariadb://localhost:3306/locations
      - MYSQL_LOC_USER=logistimo
      - MYSQL_LOC_PASS=logistimo
      - MYSQL_LOGI_HOST=jdbc:mariadb://localhost:3306/logistimo
      - MYSQL_LOGI_USER=logistimo
      - MYSQL_LOGI_PASS=logistimo
      - REDIS_HOST=localhost
      - SPRING_PROFILES_ACTIVE=dev
      - SENTINEL_HOST=
      - APP_START=true
      - ISSENTINEL=


  approvals:
    image: logistimo/approvals-service:latest
    container_name: approvals
    ports:
      - "6400:6400"
    environment:
      - SERVER_PORT=6400
      - MYSQL_HOST=jdbc:mariadb://localhost:3306/approval_service
      - MYSQL_USER=logistimo
      - MYSQL_PASSWORD=logistimo
      - CONVERSATION_SERVICE_URL=http://localhost:8080
      - ACTIVEMQ_BROKER_URL=failover:(tcp://localhost:61616)?randomize=false
      - TASK_MACHINE=true

  mapi:
    image: logistimo/ls-mobile-api:latest
    container_name: mapi
    ports:
     - "3000:3000"
    environment:
     - LOGI_HOST="http://localhost:8080/s2/api"
     - TEMP_HOST= "http://localhost:8081"
     - AMS_USER="logistimo_admin"
     - AMS_PASS="logistimo"

  collaboration:
    image: logistimo/collaboration-service:latest
    container_name: collaboration
    ports:
      - "9070:9070"
    environment:
      - MYSQL_SOCIAL_HOST=jdbc:mariadb://localhost:3306/social?useUnicode=true&amp;characterEncoding=UTF-8
      - ACTIVEMQ_URL=failover:(tcp://localhost:61616)?randomize=false
      - SERVER_PORT=9070

  logistimo:
    image: logistimo/logistimo-web-service:latest
    container_name: logi-app
    network_mode: "host"
    restart: always
    environment:
      - MYSQL_HOST_URL=jdbc:mariadb://localhost/logistimo?useUnicode=true&characterEncoding=UTF-8
      - MYSQL_RO_HOST_URL=jdbc:mariadb://localhost/logistimo?useUnicode=true&amp;characterEncoding=UTF-8
      - MYSQL_USER=logistimo
      - MYSQL_PASS=logistimo
      - REDIS_HOST=localhost
      - SENTINEL_HOST=
      - SENTINEL_MASTER=
      - HADOOP_HOST=localhost
      - MEDIA_HOST_URL=http://localhost:50070/webhdfs/v1
      - ACTIVEMQ_HOST=(tcp://localhost:61616)
      - ZKR_HOST=localhost:2181
      - LOGI_HOST=mydomain.com
      - TASK_SERVER=true
      - TASK_URL=http://localhost:8080
      - TASK_QUEUE_TYPE=jms
      - TASK_EXPORT=true
      - TASK_PORT=8080
      - EMAIL_HOST=localhost
      - EMAIL_PORT=25
      - EMAIL_FROMADDRESS=service@mydomain.com
      - EMAIL_FROMNAME=No-reply
      - CALLISTO_HOST_URL=http://localhost:9080
      - LOC_URL=http://localhost:9090
      - APPROVAL_URL=http://localhost:6400
      - COLLABORATION_URL=http://localhost:9070/v1/collaboration/likes
      - STOCKREBALANCING_URL=http://localhost:8700
      - ORIGINS=*
      - MAPI_URL=http://localhost:3000
      - CAPTCHA_ENABLE=true
      - GOOGLE_ANALYTICS_CLIENT_ID=
    volumes:
      - /data/logi-app/logs:/usr/local/tomcat/logs

  stock:
    image: logistimo/stock-rebalancing:latest
    container_name: stock
    ports:
      - "8700:8700"
    environment:
      - MYSQL_HOST=jdbc:mariadb://localhost:3306/logistimo?useUnicode=true&amp;characterEncoding=UTF-8
      - ACTIVEMQ_URL=failover:(tcp://localhost:61616)?randomize=false
      - SERVER_PORT=8700
      - MYSQL_USER=logistimo
      - MYSQL_PASSWORD=logistimo

  ams:
    image: logistimo/asset-monitoring-service:latest
    container_name: logi-ams
    ports:
     - 8081:8080
    environment:
     - MYSQL_HOST_URL=jdbc:mysql://localhost:3306/logistimo_tms
     - PUSH_TEMP_ALERT=http://localhost:8080/tempmonitoring?a=logtemp
     - MYSQL_USER=logistimo
     - MYSQL_PASS=logistimo
     - PUSH_ALARM_ALERTS=http://localhost:8080/tempmonitoring?a=logdevicealarms
     - REDIS_HOST=localhost
     - PUSH_EVENT=http://localhost:8080/s2/api/assetstatus/
     - APN_PUSH=http://localhost:8082/smsservice/devices/apn?country=%country%&phone=%phone%
     - CONFIG_PUSH_NXL=http://localhost:8082/smsservice/devices/config
     - LS_CONFIG_PUSH=http://localhost/v2/config
     - ACTIVEMQ_HOST=tcp://localhost:61616
     - ZKR_HOST=localhost:2181

  callisto:
      image: logistimo/callisto-service:latest
      container_name: callisto
      ports:
       - 9080:9080
      environment:
       - SERVER_PORT=9080
       - MONGODB_HOST=localhost
       - MONGODB_PORT=27017
       - CALLISTO_DATABASE=callisto